### ISSUE TITLE
Castlevania Symphony of the Night Saturn (VISUAL GLITCH) 

### ISSUE THREAD

**Issue by Macros218** [MiSTer-devel/Saturn_MiSTer#180] opened 2024-04-05 20:13 UTC
Hello everyone, Castlevania SOTN seems to be rendering garbled pixels at the top border of the view window. Not sure if it has to do with the way that this game is rendered or if it is related to the ram I am using.  The issue happens randomly, sometimes it appears, sometimes it does not, however it happens pretty often. The bug is present through gameplay however it does not appear in FMV scenes. It has happened in all single ram versions of the Saturn core. This is the only game that has been exhibiting this behavior.

Dual SDRAM or Single? Single 128 MB 
Link to RAM used: https://ultimatemister.com/product/xs-d128/

Core used: Saturn_unstable_20240403_13e38a.rbf

RAM Test
![20240405_160914-screen](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/166169925/582e1a9b-22e8-47e0-a28b-03ab0c865539)

How it appears in game
![20240405_154455-Bios GameNavi HiSaturn 1 03](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/166169925/76fe1cbe-9885-4119-b5bb-5d5d96fa4f1b)

![20240405_154505-Bios GameNavi HiSaturn 1 03](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/166169925/af7eabd1-ade3-455c-a490-f017f22de157)

![20240405_162146-Bios GameNavi HiSaturn 1 03](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/166169925/9bf84c18-a6f7-40fd-bcac-eaf6a765eac5)

The pixels rendered get changed after subsequent restarts.

How to replicate 

1. Use GameNavi HiSaturn 1.03 BIOS
2. Boot Castlevania Symphony of the Night (Original Japanese Version or Translation V1.02 by KNIGHTOFDRAGON)

**Comment by srg320** [comment] 2024-04-06 06:48
@Macros218, Is a keyboard connected to MiSTer?

**Comment by Zet-sensei** [comment] 2024-04-06 08:29
Same issue here.

No keyboard connected on the MiSTer.

**Comment by Kuba-J** [comment] 2024-04-06 09:24
On my side I was not able to reproduce this error , JP game version , auto region, bios unmodified JP 1.01 and GameNavi 1.03 , latest dualsdram core

**Comment by Zet-sensei** [comment] 2024-04-06 11:04
I've retried with the same config as Kuba-J.

The issue appears the first time if you launch the game on the core directly.
If you reset the core, the bug doesn't occur anymore.
The bug doesn't occur if you launched a previous game on the core too.

**Comment by Kuba-J** [comment] 2024-04-06 11:06
For me, even after the first launch, this does not occur

**Comment by Macros218** [comment] 2024-04-06 11:50
> @Macros218, Is a keyboard connected to MiSTer?

For the screenshots provided a keyboard was used alongside a controller. However, it has happened with only a USB controller plugged in as well.

**Comment by Macros218** [comment] 2024-04-06 12:46
Retested again using latest core and the same BIOS as Kuba (JP 1.01 not A revision), region set to JP, with multiple cold reboots and core reboots and it consistently minimizes the problem to one pixel. Something to note is that the pixel changes color based on what is on screen. It also removes the issue for one of the startup screens even though previously it also exhibited the same issue.

One pixel in the top left corner

![20240406_083222-Bios Saturn 1 01 (J)  !](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/166169925/f012db02-66af-40ad-9742-acacf4f6b64d)

![20240406_083335-Bios Saturn 1 01 (J)  !](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/166169925/7c5bb6d6-a377-45dd-a7a1-14de7cb68157)

![20240406_083423-Bios Saturn 1 01 (J)  !](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/166169925/3807232f-b602-44c0-a1c0-8e2fcf154074)

![20240406_083536-Bios Saturn 1 01 (J)  !](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/166169925/20971b88-2a29-405a-a38b-5861f8e9f019)

Expected Output

![20240405_204232-Bios GameNavi HiSaturn 1 03](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/166169925/ebd7bfaf-b952-4f92-8d61-f5e4d4a752e1)

**Comment by Kuba-J** [comment] 2024-04-06 12:51
Yes, i see exactly the same pixel , but no other errors

**Comment by Macros218** [comment] 2024-04-06 12:57
> Yes, i see exactly the same pixel , but no other errors

The first screenshot has a purple pixel when zoomed in, it seems to be grabbing it from the castlevania logo. The second screenshot has a grey pixel. The one with player in screen has grey pixel. In the intro scene with the horse I noticed the pixel turned green, however it was too dark to show in screenshot.

**Comment by Zet-sensei** [comment] 2024-04-06 18:26
With the 20240406 version, I also have now a consistent single pixel on cold boot & core reboot too.

**Comment by Zet-sensei** [comment] 2024-04-17 12:21
On 2024-04-17 revision (tested with a Dual RAM system, which was measured stable at 150MHz -for the two sticks-) :
- if I launch the original JP game as the first one booting on the core, the bug appears - garbled pixels at the top border of the view window;
- if I launch another game before on the core or if I even just reset the original JP game after a first boot (see above), I only have a single pixel appearing now like the other testers;
- if I launch the English translation + 4MB hack version from Meduza Team, the bug doesn't seem to be visible as the view window now fill the whole screen on top and bottom (changes done with the hack). 

EDIT : I've removed my previous comment as it wasn't precise enough.

**Comment by Zet-sensei** [comment] 2024-04-20 18:16
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/931f52a222805e6c7f77e6592a4b40d702ffa38f

**Closed** 2024-04-20 19:22 UTC
