### ISSUE TITLE
Sonic Jam: vertical distortion (like bars or slices of the image) on manuals (Japanese ISO)

### ISSUE THREAD

**Issue by FGKey2040** [MiSTer-devel/Saturn_MiSTer#153] opened 2024-03-15 15:36 UTC
Might be an artifact of how the game handles zooming? Issue is obvious when selecting virtual manuals then confirming on a page to read

**Comment by Kuba-J** [comment] 2024-03-15 15:39
Please post some pics or video, If these are lines appearing at different times, then many games have it that way

**Comment by Kuba-J** [comment] 2024-03-15 16:09
ok i see what the issue is! sometimes artifacts appear for a while

**Comment by srg320** [comment] 2024-03-18 12:43
Can you show a screenshot?

**Comment by YLFAndy** [comment] 2024-03-18 20:47
![2024031813471112](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/115659432/4f6291f2-a80b-4ebb-9582-a5c428b0ab01)

**Comment by YLFAndy** [comment] 2024-03-18 20:50
Repro steps:
Launch Sonic Jam
Choose "Game"
Pick a Genesis Sonic game
Choose Options
Choose Manual
Press R or L to flip into the manual
Press A to zoom

Result: There are vertical slices through the image

Expected: No alignment/graphical corruption issues

**Comment by real-amano** [comment] 2024-03-22 15:52
@FGKey2040 can you re-test and close the issue if it is gone?

**Comment by real-amano** [comment] 2024-04-07 09:32
@FGKey2040 can you re-test and close the issue if it is gone?

**Comment by real-amano** [comment] 2024-04-20 20:14
@FGKey2040 can you re-test and close the issue if it is gone?

**Comment by real-amano** [comment] 2024-06-17 05:32
@FGKey2040 can you re-test and close the issue if it is gone?

**Comment by real-amano** [comment] 2024-08-06 02:23
@FGKey2040 can you re-test and close the issue if it is gone?

**Comment by real-amano** [comment] 2024-08-18 19:50
@FGKey2040 can you re-test and close the issue if it is gone? According to the changelog it has been fixed many months ago.

**Comment by FGKey2040** [comment] 2024-09-01 15:06
Issue appears resolved

**Closed** 2024-09-01 15:07 UTC
