### ISSUE TITLE
Radiant Silvergun 3A boss freeze

### ISSUE THREAD

**Issue by brandon-arnold** [MiSTer-devel/Saturn_MiSTer#52] opened 2023-12-13 01:52 UTC
Hi all! I started from a save and did a perfect playthrough of level 3A. When the first boss appears, I performed the sword pincer attack and the video went garbled; see screenshot.

![image](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/7827691/e70695d2-145e-4bb8-ac49-8cf7c27ea990)

**Comment by Zet-sensei** [comment] 2024-01-11 15:13
Can't reproduce on my system, even after reading some users with problem.

DualRAM 128MB v2.9, core 20240110, stable Main 20240110
CHD version done with CHDMAN 0.261, coming from my original copy extracted in BIN+CUE (Redump) format.
Game on USB stick.
Hi-Saturn Free region BIOS.

Could you update the issue with your MiSTer system info too?
Just to have some more info and maybe find where the issue could be - by correlation between testers.
Thanks.

**Comment by real-amano** [comment] 2024-02-23 16:12
@brendon-arnold : a few months worth of fixes have passed. Can you still reproduce this issue? And if yes, can you provide your system Infos? SingleRAM? 128MB? v2.5?, core 20240223?, stable Main?

**Comment by brandon-arnold** [comment] 2024-02-23 16:28
I'm so sorry, all! I will try to repro tonight and circle back with results (and system info, if necessary).

**Comment by real-amano** [comment] 2024-03-08 05:43
@brandon-arnold , still open?

**Comment by ZmaxAldrey** [comment] 2024-03-15 17:16
The error still occurs. Core Unstable 24.03.15

**Comment by real-amano** [comment] 2024-06-16 14:18
Hmm. @brandon-arnold , @ZmaxAldrey , can this still be reproduced. As Zet-Sensei couldn't ever reproduce it, it is/was possibly single/dual RAM related and possibly fixed now.

**Comment by real-amano** [comment] 2024-06-28 19:17
Hmm. @brandon-arnold , @ZmaxAldrey , can this still be reproduced? As Zet-Sensei couldn't ever reproduce it, it is/was possibly single/dual RAM related and possibly fixed now with all that RAM reworking.

**Comment by real-amano** [comment] 2024-08-17 22:37
Hmm. @brandon-arnold , @ZmaxAldrey , can this still be reproduced? As Zet-Sensei couldn't ever reproduce it, it is/was possibly single/dual RAM related and possibly fixed now with all that RAM reworking.

**Comment by brandon-arnold** [comment] 2024-08-18 01:31
Thanks for checking again, @real-amano -- I have just done a few perfect playthroughs and haven't been able to reproduce the issue! This may have been resolved. Thanks man!

It isn't dual RAM, but it is a Jammix IO analog board.

**Comment by real-amano** [comment] 2024-08-18 08:41
@brandon-arnold great to hear. Can you close the bug then?

**Comment by brandon-arnold** [comment] 2024-08-18 14:17
> @brandon-arnold great to hear. Can you close the bug then?

Done. Sorry about that.

**Closed** 2024-08-18 14:17 UTC
