### ISSUE TITLE
Lemmings 3D Visual issues on 2D graphics on Menus/load screens.

### ISSUE THREAD

**Issue by DMJC** [MiSTer-devel/Saturn_MiSTer#44] opened 2023-11-19 12:33 UTC
Getting some sort of depth order or Z-buffer issue in Lemmings 3D on menus between levels. Ingame graphics are fine. Tested on European version.
[https://cdn.discordapp.com/attachments/1046941029296779344/1175775392318099506/20231119_230034.jpg?ex=656c752a&is=655a002a&hm=da0ba574e827cbb59b0c747ea603560a2783b3c43028cfb7196471371489c613&]

**Comment by srg320** [comment] 2024-01-12 12:59
How to reproduce this issue?

**Comment by Zet-sensei** [comment] 2024-01-13 22:07
I will try to help for documenting that issue.

We can see multiple layers of previous screens (loading screen and main title screen) mixed up with the menus.

The issue is very visible and reproductible during the title screen, with the rotating '3D' logo leaving a red trace everywhere it goes on-screnn and also on the menus (just after pressing the Start button, before entering the main game).
When moving between Lemmings characters, we can see the names of them on the end of the screen being mixed up too.

The issue is also reproductible automatically during the demo/attract mode.


![Lemmings](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/52127625/40d5f299-0604-40cf-a18e-da6ea2d9a7f8)

**Comment by srg320** [comment] 2024-01-14 08:41
Did you select the correct region in the menu?

**Comment by Zet-sensei** [comment] 2024-01-14 09:52
Thanks for the reply.

You must force use the 'Europe' region on the core.
Fixed with your indication, could be closed.

Solution tested with a European BIOS & a multi-region hacked Hi-Saturn BIOS.

**Comment by Zet-sensei** [comment] 2024-10-30 12:36
Should be closed since then & positive tests performed by multiple people during the same time.

**Closed** 2024-10-30 12:40 UTC
