### ISSUE TITLE
MK2 crashes when performing a fatality on US version. 

### ISSUE THREAD

**Issue by Gouki94** [MiSTer-devel/Saturn_MiSTer#19] opened 2023-10-12 13:46 UTC
Tested with Scorpion on pit stage. US Romset

**Comment by Fonsie001** [comment] 2024-02-13 17:26
Hello, tried it on the dual ram version 20240212_18e57f the issue still exists, mostly with pit fatalities but also regular fatalities but that happens less

**Comment by srg320** [comment] 2024-07-21 10:58
How to reproduce this issue? How to make fatalities?

**Comment by Fonsie001** [comment] 2024-07-21 22:29
Issue is resolved in later versions of the core, tested it on Saturn_DualSDRAM_unstable_20240628_13e17d.rbf and this issue did not occur

**Comment by real-amano** [comment] 2024-07-22 06:45
@Gouki94 , can you test it again and close the issue?

**Comment by real-amano** [comment] 2024-07-23 19:05
@Gouki94 , can you test it again and close the issue?

**Comment by real-amano** [comment] 2024-08-24 12:16
@Gouki94 , since this issue seems to be fixed since at least July can you test the game again and close the issue?

**Comment by Gouki94** [comment] 2024-08-25 09:38
Issue resolved in latest build, please close

**Comment by Kuba-J** [comment] 2024-08-25 09:44
> Issue resolved in latest build, please close

I think you can close this case :) 

![image](https://github.com/user-attachments/assets/2c8ef92f-6c00-4125-afea-71d8d7ed67c5)

**Closed** 2024-08-25 10:06 UTC
